### ISSUE TITLE
Only works properly with active internet connection

### ISSUE THREAD

**Issue by trys7382** [lstein/PhotoMapAI#111]
I've installed it manually on Windows and saw that it doesn't work if you have no internet connection. I'm able to start the PhotoMap server and open it on the local host address in the browser but the semantic map remains empty and it doesn't show any of the already created albums. Indexing new albums however works. Only when I connect to the internet then albums/maps are shown. But this seems strange to me as it should only run on the local host?

(It's btw. a neat little tool, like it so far!)

**Comment by lstein** [comment]
The very first time you run PhotoMap after a manual install, it will download the CLIP image recognition model over the internet. If the network is inaccessible, this step will fail. There will be an error in the server log, but no message will appear in the browser (I will fix that). However, after this first run, you shouldn't need internet connectivity. 

I'm gathering that you're seeing something different -- the server works properly when the internet is connected, but when you disconnect it the albums and their maps disappear. Is that the scenario? 

Unfortunately I haven't been able to reproduce this so far. It could help if you add screenshots of the empty map, the settings dialog's album menu, and the album manager window. Also, do you see any error messages in the command-line window where you launch the server?

**Comment by lstein** [comment]
Thanks very much for the screenshots and logs. I think that what’s happening is that the client-side code (running on the browser) needs to pull in a few external libraries from the Internet before it can display the semantic map. I will convert the code to use locally-stored libraries and this should fix the problem.

**Comment by lstein** [comment]
I have updated the application to use local Javascript libraries rather than download them from the Internet. This should fix the errors you are experiencing.

**Comment by kamikatze13** [comment]
@lstein I don't know what happened to that PR #112 but I can confirm the fix didn't make it into the master branch as of version 1.0 so the issue is still very much open. The current state of `/photomap/frontend/templates/main.html` unfortunately still references external resources =/

I had to download external files and manually modify `main.html`, so the supposed fix should theoretically work.
